#%RAML 1.0
---
title: Book Management API
version: v1
baseUri: http://localhost:3000/api/v1
mediaType: application/json

types:
  Book:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      author:
        type: string
      isbn:
        type: string
      publishYear:
        type: integer
      price:
        type: number
      category:
        type: string

  CreateBookRequest:
    type: object
    properties:
      title:
        type: string
      author:
        type: string
      isbn:
        type: string
      publishYear:
        type: integer
      price:
        type: number
      category:
        type: string

  ListBooksResponse:
    type: object
    properties:
      books:
        type: Book[]
      total:
        type: integer

/books:
  get:
    displayName: List all books
    queryParameters:
      category:
        type: string
        required: false
      limit:
        type: integer
        required: false
        default: 10
      offset:
        type: integer
        required: false
        default: 0
    responses:
      200:
        body:
          application/json:
            type: ListBooksResponse

  post:
    displayName: Create a new book
    body:
      application/json:
        type: CreateBookRequest
    responses:
      201:
        body:
          application/json:
            type: Book

  /{id}:
    get:
      displayName: Get book by ID
      uriParameters:
        id:
          type: string
          required: true
      responses:
        200:
          body:
            application/json:
              type: Book

    put:
      displayName: Update book
      uriParameters:
        id:
          type: string
          required: true
      body:
        application/json:
          type: CreateBookRequest
      responses:
        200:
          body:
            application/json:
              type: Book

    delete:
      displayName: Delete book
      uriParameters:
        id:
          type: string
          required: true
      responses:
        204:
