from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book import Book
from openapi_server import util

from openapi_server.models.book import Book  # noqa: E501

class BooksGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, books=None, total=None):  # noqa: E501
        """BooksGet200Response - a model defined in OpenAPI

        :param books: The books of this BooksGet200Response.  # noqa: E501
        :type books: List[Book]
        :param total: The total of this BooksGet200Response.  # noqa: E501
        :type total: int
        """
        self.openapi_types = {
            'books': List[Book],
            'total': int
        }

        self.attribute_map = {
            'books': 'books',
            'total': 'total'
        }

        self._books = books
        self._total = total

    @classmethod
    def from_dict(cls, dikt) -> 'BooksGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _books_get_200_response of this BooksGet200Response.  # noqa: E501
        :rtype: BooksGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def books(self) -> List[Book]:
        """Gets the books of this BooksGet200Response.


        :return: The books of this BooksGet200Response.
        :rtype: List[Book]
        """
        return self._books

    @books.setter
    def books(self, books: List[Book]):
        """Sets the books of this BooksGet200Response.


        :param books: The books of this BooksGet200Response.
        :type books: List[Book]
        """

        self._books = books

    @property
    def total(self) -> int:
        """Gets the total of this BooksGet200Response.


        :return: The total of this BooksGet200Response.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this BooksGet200Response.


        :param total: The total of this BooksGet200Response.
        :type total: int
        """

        self._total = total
